# Generated by Django 4.2.2 on 2023-07-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmmt',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
